config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'top/login' => 'top#login'
  post 'top/auth' => 'top#auth'
  resource :user do
    patch 'logout' => 'users#logout'
  end
  resources :groups do
    collection { get 'search' }
    member do
      get 'reception' # グループ参加確認ページ
      post 'join'     # グループ参加処理
    end
    resources :tasks
    resources :grades, only: [:index, :create]
    resources :messages, only: [:index, :new, :create]
    resources :members, only: :index do
      collection { patch 'addmin'}  # 管理者を増やす処理
    end
    resources :users_tasks, only: [:index, :show, :update] do
      collection { patch 'confirm'} # タスク確認処理
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group
  has_many :users_tasks
  has_many :users, through: :users_tasks

  # *** バリデーション ***
  validates :title,
    presence: { message: '必須です'},
    length: { maximum: 120, message: 'タイトルは120文字以内です'}
  validates :points,
    inclusion: {
      in: 0..30000,
      allow_nil: true
    }
  validates :importance,
    inclusion: {
      in: 1..10,
    }
end

app/controllers/tasks_controller.rb
class TasksController < OnGroupsController
  layout 'group'
  before_action :check_admin

  def index
    @tasks = Task.where(group: @group)
                .page(params[:page])
                .per(10)
                .order(updated_at: :desc)
  end

  def show
    @task = Task.includes(:users).find(params[:id])
    @finished_u_tasks = @task.users_tasks.select{|ut| ut.state == UsersTask::STATE_FINISHED}
    @unfinished_u_tasks = @task.users_tasks.select{|ut| ut.state == UsersTask::STATE_UNFINISHED}
    @confirmed_u_tasks = @task.users_tasks.select{|ut| ut.state == UsersTask::STATE_CONFIRMED}
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    return render :new unless @task.valid?

    Task.transaction do
      @task.save!
      @group.not_admins.each do |m|
        m.tasks << @task
      end
      @group.messages.create!(body: "新タスク「#{@task.title}」が生成されました")
    end
    if params[:mail]
      to = @group.members.map {|m| m.email }
      NoticeMailer.task_created(@task, to).deliver
    end
    redirect_to action: :index
  end

  private

  def tasks_params
    params.require(:task).permit(
      :title,
      :detail,
      :deadline,
      :importance,
      :points
    ).merge(group: @group, author: @user)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def importance_to_class_name(importance)
    case importance
    when 1, 2
      'importance_1_2'
    when 3, 4
      'importance_3_4'
    when 5, 6
      'importance_5_6'
    when 7, 8
      'importance_7_8'
    else
      'importance_9_X'
    end
  end
end

app/views/tasks/_task_outline.html.erb
<article class="task_outline">
  <a href="<%= to %>">
    <h1 class="<%= importance_to_class_name(task.importance) %>">
      <%= task.title %>
    </h1>
    <table class="table">
      <tr>
        <th>期限</th><td><%= task.deadline.nil? ? 'なし' : task.deadline.strftime('%Y年%m月%d日 %H:%M') %></td>
      </tr>
      <tr>
        <th>重要度</th><td><%= task.importance %></td>
      </tr>
      <tr>
        <th>獲得ポイント</th><td><%= task.points %>pt</td>
      </tr>
      <% if defined? finished_at %>
        <tr>
          <th>完了日時</th><td><%= finished_at.strftime '%Y年%m月%d日 %H:%M' %></td>
        </tr>
      <% end %>
    </table>
  </a>
</article>

app/views/tasks/index.html.erb
<section id="tasks_index" class="container">
  <%= link_to 'タスクを新規作成', new_group_task_path(@group), class: 'btn btn-success'%>
  <% @tasks.each do |task| %>
    <%= render 'tasks/task_outline', task: task, to: group_task_path(@group, task.id) %>
  <% end %>
  <%= paginate @tasks %>
</section>

app/views/tasks/new.html.erb
<% provide :title, "タスク新規作成" %>
<section id="tasks_new" class="container">
  <div class="row">
    <h1 class="col-sm-offset-3 col-sm-5 text-center">タスク作成</h1>
  </div>
  <%= form_for @task, url: { action: :create }, html: {class: 'form-horizontal'} do |f| %>
    <% e = @task.errors %>
    <%= bs_form_group messages: e[:title] do |msgs| %>
      <%= f.label :title, 'タイトル', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.text_field :title, maxlength: 120, class: 'form-control', tabindex: 1 %>
        <%= msgs.call %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <%= f.label :detail, '説明', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.text_area :detail, maxlength: 32000, class: 'form-control', tabindex: 2 %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <%= f.label :deadline, '期限', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.datetime_local_field :deadline, class: 'form-control', tabindex: 3 %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <%= f.label :importance, '重要度', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.select :importance, 1..10, selected: 3, class: 'form-control', tabindex: 4 %>
      </div>
    <% end %>
    <%= bs_form_group messages: e[:points] do |msgs| %>
      <%= f.label :points, '獲得ポイント', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.number_field :points, min: 0, max: 30000, value: 0, class: 'form-control', tabindex: 5 %>
        <%= msgs.call %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <label class="control-label col-sm-3">通知メールを送る</label>
      <div class="col-sm-5">
        <%= check_box_tag :mail, true, false, tabindex: 6 %>
        <div class="form-text text-muted">チェックした場合はメンバー全員にメールが送信されます</div>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <div class="col-sm-offset-3 col-sm-5">
        <%= f.submit '作成する', class: 'btn btn-success btn-block' %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/tasks/show.html.erb
<section id="tasks_show" class="container">
  <article>
    <h1 class="<%= importance_to_class_name(@task.importance) %>">
      <%= @task.title %>
   </h1>
    <pre><%= @task.detail %></pre>
    <table class="table table-condensed">
      <tr><th>作成者</th><td><%= @task.author.name %></td></tr>
      <tr><th>作成日</th><td><%= @task.created_at.strftime('%Y年%m月%d日 %H:%M')%></td></tr>
      <tr><th>期限</th><td><%= @task.deadline.strftime('%Y年%m月%d日 %H:%M') rescue 'なし'%></td></tr>
      <tr><th>重要度</th><td><%= @task.importance %></td></tr>
      <tr><th>獲得ポイント</th><td><%= @task.points || 'なし' %></td></tr>
    </table>
  </article>
  <%= form_tag({ controller: :users_tasks, action: :confirm }, method: :patch) do %>
  <%= hidden_field_tag :task, @task.id %>
    <div class="panel panel-default">
      <%= submit_tag '確認済みにする', class: 'btn btn-success', disabled: @finished_u_tasks.empty? %>
      <div class="panel-heading">完了済みのメンバー</div>
      <table class="table">
        <tr><th>確認</th><th>名前</th><th>完了日時</th></tr>
        <% if @finished_u_tasks.empty? %>
          <tr><td>完了しているメンバーはいません</td></tr>
        <% end %>
        <% @finished_u_tasks.each do |ut| %>
          <tr>
            <td><%= check_box_tag 'users_tasks[]', ut.id, true %></td>
            <td><%= ut.user.name %></td>
            <td><%= ut.finished_at.strftime('%Y年%m月%d日 %H:%M') %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading">未完了のメンバー</div>
    <table class="table">
      <tr><th>名前</th></tr>
      <% if @unfinished_u_tasks.empty? %>
        <tr><td>未完了メンバーはいません</td></tr>
      <% end %>
      <% @unfinished_u_tasks.each do |ut| %>
        <tr>
          <td><%= ut.user.name %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">確認したメンバー</div>
    <table class="table">
      <tr><th>名前</th></tr>
      <% if @confirmed_u_tasks.empty? %>
        <tr><td>確認したメンバーはいません</td></tr>
      <% end %>
      <% @confirmed_u_tasks.each do |ut| %>
        <tr>
          <td><%= ut.user.name %></td>
        </tr>
      <% end %>
    </table>
  </div>
</section>