config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'top/login' => 'top#login'
  post 'top/auth' => 'top#auth'
  resource :user do
    patch 'logout' => 'users#logout'
  end
  resources :groups do
    collection { get 'search' }
    member do
      get 'reception' # グループ参加確認ページ
      post 'join'     # グループ参加処理
    end
    resources :tasks
    resources :grades, only: [:index, :create]
    resources :messages, only: [:index, :new, :create]
    resources :members, only: :index do
      collection { patch 'addmin'}  # 管理者を増やす処理
    end
    resources :users_tasks, only: [:index, :show, :update] do
      collection { patch 'confirm'} # タスク確認処理
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :users_groups, -> {order(total_points: :desc)}
  has_many :members, through: :users_groups, class_name: 'User', source: :user
  has_many :admins, -> { where(users_groups: {admin: true}) }, through: :users_groups, class_name: 'User', source: :user
  has_many :not_admins, -> { where(users_groups: {admin: false}) }, through: :users_groups, class_name: 'User', source: :user
  has_many :tasks
  has_many :messages, -> {order(created_at: :desc)}
  has_many :grades, -> {order(necessary_points: :desc)}, dependent: :destroy

  # *** バリデーション ***
  validates :name,
    presence: { message: '必須です' },
    length: { maximum: 40, allow_blank: true,
      message: 'グループ名は40文字以内です' }
  validates :password,
    presence: { message: '必須です', if: 'private' },
    confirmation: { message: 'パスワード（確認用）と相違があります' },
    length: { within: 8..40, allow_blank: true, message: 'パスワード長は8文字以上です' }
end

app/controllers/groups_controller.rb
class GroupsController < OnGroupsController
  skip_before_action :check_joined, except: [:show, :edit, :update, :destroy]
  layout 'group', only: [:show, :edit]

  def index
    # 参加しているグループとその作成者をあらかじめ読み込む。(n+1問題対策)
    @user = User.includes(joined_groups: :author).find(@user.id)
  end

  def show
  end

  def new
    @new_group = Group.new
  end

  def create
    #ユーザが入力した値を取得
    params = groups_params
    # グループの作成者を設定（ログインユーザ）
    params.store :author, logined_user
    # グループオブジェクト作成
    @new_group = Group.new(params)

    # ユーザの入力に誤りがあった場合は作成ページに戻る
    return render :new unless @new_group.valid?

    # 作成したグループをDBに反映する。同時に、作成者をそのグループのメンバーとする
    Group.transaction do
      @new_group.save! validate: false
      UsersGroup.create!(user: @new_group.author, group: @new_group, admin: true)
      @new_group.messages.create!(body: "「#{@new_group.name}」が結成されました。")
    end
  end

  def search
    case params[:search_type]
    when 'id' then
      where_args = [ { id: params[:input_text] } ]
    when 'keyword' then
      keyword = "%#{params[:input_text]}%"
      # HACK: Arel API使うべき?
      where_args = [ 'name LIKE ? OR detail LIKE ?', keyword, keyword ]
    else # 指定されていない。又は不正な値
      return
    end

    # 最大10件ごとにページネーションするように取得
    @groups = Group.includes(:author).where(*where_args)
                .page(params[:page])
                .per(10)
                .order(:id)
  end

  def reception
    @group = Group.find(params[:id])
    # 当該グループに、既に参加していた場合はshowにリダイレクト
    redirect_to group_path(@group) if @group.members.exists?(@user)
  end

  def join
    @group = Group.find(params[:id])
    if @group.password == params[:password]
      UsersGroup.create!(user: @user, group: @group, admin: false)
    else
      @alert = 'パスワードが間違っています。'
      render :reception
    end
  end

  private

  def groups_params
    params.require(:group).permit(
      :name,
      :detail,
      :private,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_outline.html.erb
<% to ||= group_path(group) %>
<article class="group_outline">
  <header>
    <div class="private_icon">
      <%= glyphicon(group.private ? 'lock' : 'globe') %>
    </div>
    <h2><%= link_to group.name, to %></h2>
    ID: <%= group.id %>
  </header>
  <pre><%= group.detail %></pre>
  <footer>作成者: <%= group.author.name %></footer>
</article>

app/views/groups/create.html.erb
<section class="container">
  <h1>新規グループ「<%= @new_group.name %>」を作成しました。</h1>
  <p>以下のグループIDを参加者にお伝えください。</p>
  <h2>グループID: 「<%= @new_group.id %>」</h2>
  <p>なお、グループにパスワードを設定している場合は、そちらもご一緒にお伝えください。</p>
</section>

app/views/groups/index.html.erb
<% provide :title, "グループ一覧" %>
<div id="groups_index" class="container">
  <h1>グループ一覧</h1>
  <div class="row">
    <% @user.joined_groups.each do |group| %>
    <div class="col-md-4">
      <%= render 'groups/group_outline', group: group %>
    </div>
    <% end %>
    <div class="col-md-4">
      <article>
        <%= link_to search_groups_path, class: 'btn btn-primary btn-block' do %>
          <span class="btn_icon"><%= glyphicon('share-alt') %></span><br />
          他のグループに参加
        <% end %>
      </article>
    </div>
    <div class="col-md-4">
      <article>
        <%= link_to new_group_path, class: 'btn btn-success btn-block' do %>
          <span class="btn_icon"><%= glyphicon('plus-sign') %></span><br />新しいグループを作成
        <% end %>
      </article>
    </div>
  </div>
</div>

app/views/groups/join.html.erb
<% provide :title, "参加完了" %>
<section id="groups_join" class="container">
  <h1><%= @group.name %>に参加しました。</h1>
  <%= link_to "#{@group.name}のページへ", group_path(@group) %>
</section>

app/views/groups/new.html.erb
<% provide :title, "グループ作成" %>
<section id="groups_new" class="container">
  <div class="row">
    <h1 class="col-sm-offset-3 col-sm-5">グループ作成</h1>
  </div>
  <%= form_for @new_group, url: { action: :create }, html: {class: 'form-horizontal'} do |f| %>
    <% e = @new_group.errors %>
    <%= bs_form_group messages: e[:name] do |msgs| %>
      <%= f.label :name, 'グループ名', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.text_field :name, maxlength: 40, class: 'form-control', tabindex: 1 %>
        <%= msgs.call %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <%= f.label :detail, 'グループの説明', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.text_area :detail, maxlength: 32000, class: 'form-control', tabindex: 2 %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <div class="col-sm-offset-3 col-sm-5">
        <%= f.check_box :private, tabindex: 3, checked: true %>
        <%= f.label :private, 'パスワードを設定する' %>
        <div class="form-text text-muted">設定しなかった場合は、誰でも参加できるグループとなります。</div>
      </div>
    <% end %>
    <%= bs_form_group messages: e[:password] do |msgs| %>
      <%= f.label :password, 'パスワード', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.password_field :password, maxlength: 40, class: 'form-control', tabindex: 4 %>
        <%= msgs.call %>
      </div>
    <% end %>
    <%= bs_form_group messages: e[:password_confirmation] do |msgs| %>
      <%= f.label :password_confirmation, 'パスワード(確認用)', class: 'control-label col-sm-3' %>
      <div class="col-sm-5">
        <%= f.password_field :password_confirmation, maxlength: 40, class: 'form-control', tabindex: 4 %>
        <%= msgs.call %>
      </div>
    <% end %>
    <%= bs_form_group do %>
      <div class="col-sm-offset-3 col-sm-5">
        <%= f.submit '作成する', class: "btn btn-success btn-block" %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/groups/reception.html.erb
<% provide :title, "参加確認" %>
<section id="groups_reception" class="container">
  <%= render 'groups/group_outline', group: @group, to: 'javascript:void(0);'%>
  <h2>このグループに参加しますか?</h2>
  <%= form_tag join_group_path(@group) do %>
    <% if @group.private? %>
      <%= bs_form_group messages: @alert do |msg| %>
        <%= label_tag :password, 'パスワード', class: 'control-label'%>
        <div class="row">
          <div class="col-sm-4">
            <%= password_field_tag :password, '', class: 'form-control' %>
            <%= msg.call %>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= bs_form_group do %>
      <%= submit_tag '参加する', class: 'btn btn-primary' %>
      <%= link_to '参加しない（戻る）', :back, class: 'btn btn-default' %>
    <% end %>
  <% end %>
</section>

app/views/groups/search.html.erb
<% provide :title, "グループ検索" %>
<section id="groups_search" class="container">
  <h1>グループ検索</h1>
  <%= form_tag search_groups_path, method: :get do %>
    <label><%= radio_button_tag :search_type, 'keyword', checked: true %>キーワードで探す</label>
    <label><%= radio_button_tag :search_type, 'id' %>グループIDで探す</label>
    <%= text_field_tag :input_text, params[:input_text], placeholder: 'キーワードを入力' %>
    <%= submit_tag '検索' %>
  <% end %>
  <% unless @groups.nil? %>
    <% if @groups.empty? %>
      <div>検索条件に合致するグループはありませんでした。</div>
    <% else %>
      <% @groups.each do |group| %>
        <%= render 'groups/group_outline', group: group %>
      <% end %>
      <div id="pagination">
        <%= paginate @groups %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/groups/show.html.erb
<% provide :title, @group.name %>
<section id="groups_show" class="container">
  <article class="panel panel-primary">
    <div class="panel-heading">
      <h1><%= @group.name %></h1>
    </div>
    <pre><%= @group.detail %></pre>
    <table class="table">
      <tr>
        <th>作成者</th>
        <td><%= @group.author.name %></td>
      </tr>
      <tr>
        <th>作成日</th>
        <td><%= @group.created_at.strftime('%Y年%m月%d日') %></td>
      </tr>
      <tr>
        <th>管理者</th>
        <td><%= @group.admins.map{|a|a.name}.join(', ') %></td>
      </tr>
      <tr>
        <th>全人数</th>
        <td><%= @group.members.size %>人</td>
      </tr>
    </table>
  </article>
</section>