config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'top/login' => 'top#login'
  post 'top/auth' => 'top#auth'
  resource :user do
    patch 'logout' => 'users#logout'
  end
  resources :groups do
    collection { get 'search' }
    member do
      get 'reception' # グループ参加確認ページ
      post 'join'     # グループ参加処理
    end
    resources :tasks
    resources :grades, only: [:index, :create]
    resources :messages, only: [:index, :new, :create]
    resources :members, only: :index do
      collection { patch 'addmin'}  # 管理者を増やす処理
    end
    resources :users_tasks, only: [:index, :show, :update] do
      collection { patch 'confirm'} # タスク確認処理
    end
  end
end

app/models/users_task.rb
class UsersTask < ApplicationRecord
  belongs_to :user
  belongs_to :task

  scope :group_is, -> (group) { joins(:task).where(tasks: {group: group}) }

  STATE_UNFINISHED = 0  # 未完了
  STATE_FINISHED = 1    # 完了
  STATE_CONFIRMED = 2   # 確認済
end

app/controllers/users_tasks_controller.rb
class UsersTasksController < OnGroupsController
  layout 'group'
  before_action :check_admin, only: :confirm

  def index
    key, type = (params[:order] || 'deadline_asc').split('_')

    users_tasks = UsersTask.group_is(@group).where(user: @user).order("tasks.#{key} #{type}")

    @unfinished_u_tasks = users_tasks.select {|ut| ut.state == UsersTask::STATE_UNFINISHED}
    @finished_u_tasks = users_tasks.select {|ut| ut.state == UsersTask::STATE_FINISHED}
    @confirmed_u_tasks = users_tasks.select {|ut| ut.state == UsersTask::STATE_CONFIRMED}
  end

  def show
    @users_task = UsersTask.find(params[:id])
  end

  def update
    users_task = UsersTask.find(params[:id])
    return unless users_task.user_id == @user.id

    case params[:state]
    when 'unfinished'
      users_task.state = UsersTask::STATE_UNFINISHED
      users_task.finished_at = nil
      users_task.save!
      redirect_to({action: :show}, notice: '未完了にしました。')
    when 'finished'
      users_task.state = UsersTask::STATE_FINISHED
      users_task.finished_at = Time.current
      users_task.save!
      redirect_to({action: :show}, notice: '完了にしました。')
    end
  end

  def confirm
    users_tasks = UsersTask.where(id: params[:users_tasks])
    UsersTask.transaction do
      users_tasks.each do |ut|
        ut.state = UsersTask::STATE_CONFIRMED
        UsersGroup.where(group: @group).where(user: ut.user).first
            .increment!(:total_points, ut.task.points)
        ut.save!
      end
    end
    redirect_to controller: :tasks, action: :show, id: params[:task]
  end
end

app/helpers/users_tasks_helper.rb
module UsersTasksHelper
end

app/views/users_tasks/index.html.erb
<section id="users_tasks_index" class="container">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#unfinished" data-toggle="tab">未完了のタスク</a></li>
    <li><a href="#finished" data-toggle="tab">完了</a></li>
    <li><a href="#confirmed" data-toggle="tab">完了&amp;確認済</a></li>
  </ul>
  <section class="tab-content">
    <%= form_tag group_users_tasks_path(@group), method: :get, id: :order_form do %>
      <select name="order">
        <option value="deadline_asc">期限が近い順</option>
        <option value="deadline_desc">期限が遠い順</option>
        <option value="importance_asc">重要度が低い順</option>
        <option value="importance_desc">重要度が高い順</option>
        <option value="points_asc">獲得ポイントが低い順</option>
        <option value="points_desc">獲得ポイントが高い順</option>
      </select>
    <% end %>
    <div id="unfinished" class="tab-pane fade in active">
      <% @unfinished_u_tasks.each do |ut| %>
        <%= render 'tasks/task_outline', task: ut.task, to: group_users_task_path(@group, ut) %>
      <% end %>
    </div>
    <div id="finished" class="tab-pane fade">
      <% @finished_u_tasks.each do |ut| %>
        <%= render 'tasks/task_outline', task: ut.task, finished_at: ut.finished_at, to: group_users_task_path(@group, ut) %>
      <% end %>
    </div>
    <div id="confirmed" class="tab-pane fade">
      <% @confirmed_u_tasks.each do |ut| %>
        <%= render 'tasks/task_outline', task: ut.task, finished_at: ut.finished_at, to: group_users_task_path(@group, ut) %>
      <% end %>
    </div>
  </section>
</section>

app/views/users_tasks/show.html.erb
<% task = @users_task.task %>
<section id="users_tasks_show" class="container">
  <% if notice %>
    <div class="alert alert-success">
      <button class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% end %>
  <article>
    <% case @users_task.state %>
    <% when UsersTask::STATE_UNFINISHED %>
      <button class="btn btn-primary" id="state" data-state="unfinished">完了にする</button>
    <% when UsersTask::STATE_FINISHED %>
        <button class="btn btn-warning" id="state" data-state="finished">未完了にする</button>
    <% when UsersTask::STATE_CONFIRMED %>
      <button id="state" data-state="confirmed" class="btn btn-default disabled">確認済み</button>
    <% end %>
    <h1 class="<%= importance_to_class_name(task.importance) %>">
      <%= task.title %>
   </h1>
    <pre><%= task.detail %></pre>
    <table class="table table-condensed">
      <tr><th>作成者</th><td><%= task.author.name %></td></tr>
      <tr><th>作成日</th><td><%= task.created_at.strftime('%Y年%m月%d日 %H:%M')%></td></tr>
      <tr><th>期限</th><td><%= task.deadline.strftime('%Y年%m月%d日 %H:%M')%></td></tr>
      <tr><th>重要度</th><td><%= task.importance %></td></tr>
      <tr><th>獲得ポイント</th><td><%= task.points || 'なし' %></td></tr>
    </table>
  <article>
<%= form_tag({action: :update}, method: 'patch', id: 'state_change_form') do %>
  <%= hidden_field_tag 'state', '', id: 'hidden_state'%>
<% end %>
</section>