config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'top/login' => 'top#login'
  post 'top/auth' => 'top#auth'
  resource :user do
    patch 'logout' => 'users#logout'
  end
  resources :groups do
    collection { get 'search' }
    member do
      get 'reception' # グループ参加確認ページ
      post 'join'     # グループ参加処理
    end
    resources :tasks
    resources :grades, only: [:index, :create]
    resources :messages, only: [:index, :new, :create]
    resources :members, only: :index do
      collection { patch 'addmin'}  # 管理者を増やす処理
    end
    resources :users_tasks, only: [:index, :show, :update] do
      collection { patch 'confirm'} # タスク確認処理
    end
  end
end

app/views/layouts/_logined_nav.html.erb
<div class="container">
  <div class="navbar-header" style='float: left'>
    <%= link_to 'Homework Manager', root_path, id: 'common_nav_brand', class: 'navbar-brand' %>
  </div>
  <div id="common_nav_user" class="btn-group pull-right">
    <button class="btn btn-primary dropdown-toggle navbar-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= glyphicon('user') %>
      <span class="hidden-xs"><strong><%= user.name %></strong>さん</span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li class="dropdown-header visible-xs">
        <strong><%= user.name %></strong>さん
      </li>
      <li>
        <%= link_to groups_path do %>
          <%= glyphicon('flag') %> グループ一覧
        <% end %>
      </li>
      <li>
        <%= link_to search_groups_path do %>
          <%= glyphicon('search') %> グループ検索
        <% end %>
      </li>
      <li>
        <%= link_to user_path do %>
          <%= glyphicon('home') %> ユーザ情報
        <% end %>
      </li>
      <li>
        <%= link_to logout_user_path, method: :patch do %>
          <%= glyphicon('log-out') %> ログアウト
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_not_logined_nav.html.erb
<div class="container">
  <div class="navbar-header">
    <%= link_to 'Homework Manager', root_path, id: 'common_nav_brand', class: 'navbar-brand' %>
    <button id="common_nav_toggle" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#common_nav_target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="common_nav_target">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'ログイン', top_login_path, class: 'text-center' %></li>
      <li><%= link_to '新規登録', new_user_path, class: 'text-center' %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= title(yield :title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <nav id="common_nav" class="navbar navbar-default">
      <% if @user # ログイン状態だった場合のナビバー%>
        <%= render 'layouts/logined_nav', user: @user %>
      <% else # 非ログイン状態だった場合のナビバー%>
        <%= render 'layouts/not_logined_nav' %>
      <% end %>
    </nav>


    <%= content_for?(:group) ? yield(:group) : yield %>


    <footer id="common_footer">
      <div class="container">
        <small class="text-muted">&copy; 2016 Homework Management Systems</small>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/group.html.erb
<% # このレイアウトを使用する場合は@group, @userがコントローラ側で設定されていなければならない
  admin = @user.is_admin_with(@group)
  list_items = [
    {
      disp: 'タスク',
      path: admin ? group_tasks_path(@group) : group_users_tasks_path(@group),
      ctrl: 'users_tasks'
    }, {
      disp: 'メッセージボード',
      path: group_messages_path(@group),
      ctrl: 'messages'
    }, {
      disp: 'ランキング',
      path: group_members_path(@group),
      ctrl: 'members'
    }, {
      disp: 'レベル',
      path: group_grades_path(@group),
      ctrl: 'grades'
    }, {
      disp: 'グループ説明',
      path: group_path(@group),
      ctrl: 'groups'
    },
  ]
%>
<% content_for :group do %>
  <div id="layouts_group">
    <div id="bg_image">
      <section class="container">
        <article id="group_heading">
          <p id="today"><%= Time.current.strftime('%Y年%m月%d日') %></p>
          <h1 id="group_name"><%= @group.name %></h1>
          <p>作成者:<%= @group.author.name %></p>
        </article>
        <article id="user_heading">
          <h2><%= @user.name %></h2>
          <% if admin %>
            <p>管理者<p>
          <% elsif grade = @user.grade_with(@group) %>
            <p><%= "レベル: #{grade.name}" %></p>
          <% end %>
        </article>
      </section>
    </div>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <% list_items.each do |li| %>
            <%= content_tag :li, class: li[:ctrl].include?(controller_name) ? 'active' : nil do %>
              <%= link_to li[:disp], li[:path] %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <%= yield %>

<% end %>
<%= render template: 'layouts/application' %>